services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: sicoa_app
    user: "${APP_UID}:${APP_UID}"
    volumes:
      - ../ventas-web:/var/www/html
      - ./docker/php/custom-php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      APP_USER: ${APP_USER}
      APP_UID: ${APP_UID}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:80"
      - "5173:5173"
    depends_on:
      - db
    working_dir: /var/www/html
    networks:
      - pi-network

  db:
    image: mysql:8.0
    container_name: data_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME_APP}
      MYSQL_PASSWORD: ${DB_PASSWORD_APP}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - pi-network

networks:
  pi-network:
    driver: bridge